### PR TITLE
Optional Exif Info in album pages

### PR DESCRIPTION
**Pull request by Hard-One**
This PR makes it possible to select from theme settings wether you want to show Exif Info inside the image overlay or not.

Hope you like it.

### CODE REVIEW

**Comment by BlackSkorpio** [comment]
Waiting a bit with this one....

Need to see, "in works"
Plus it has to have own setting.

**Comment by Hard-One** [comment]
I've bound it to "Show Img Info" option within theme settings.
img_info_setting

But I'm glad you did not merge it. Seems I was a bit to quick. There's some CSS work left to ensure compatibility across different devices/resolutions.

**Comment by BlackSkorpio** [comment]
I noticed :)

But it should be a separate setting for this, since there just a very small percentage that would actually enable it.
The most users that use EXIF want to display that info together with other image details: ie on contents.lens or in the lightbox (the last is also a very small percentage that do).

I am actually considering separate settings for lightbox.lens and content.lens: just to let the admin decided what and where to display any info.

**Comment by Hard-One** [comment]
Seperate settings for lightbox and other templates would be great, but also sounds like a lot of work to do. I really like the idea to be abled to decide where to display what on a per template basis.
However I think that there are other settings being actually more important than this. For example I'm thinking of being able to select the colors the theme uses. Setting background and text colors would be really cool and used by more people than displaying arbitrary exif infos.
For us being able to code it's no big deal to show some exif info somewhere, but for those non-coders it's a pain to change the background on the whole site.

**Comment by BlackSkorpio** [comment]
I agree...

The ability to changera colors and fonts is something i in the "pipe-line": but first I want to polish and refine the current state...
Making it really solid both when it comes to the code and CSS :)

**Comment by BlackSkorpio** [comment]
Btw 
Where are you regarding the German branch?

**Comment by BlackSkorpio** [comment]
ATM a "hidden" feature of OxyGen 3
To enable use:

```
span.inline_exif{
    display: table;
}
```

**Comment by BlackSkorpio** [comment]
With the above I'm closing this

**Pull request closed without merging**
